### ISSUE TITLE
Batch Delete Throws Error: Requested value 'DELETE' was not found

### ISSUE THREAD

**Issue by bafadam** [Saleslogix/DotNetSDataClient#10]
Using the batch object and trying to DeleteAll, throws an argument error "Requested value 'DELETE' was not found."

var batch = client.CreateBatch<SlxAccount>();
batch.DeleteAll(accountsToDelete);
batch.Commit();

Single object deletes don't have a problem, it's just the batch delete method, and interestingly enough, the batch process still commits, it's just the after processing which seems not to be passing something somewhere.

Thanks!

**Comment by NathanBaulch** [comment]
Good catch, fixed in version 2.0.1.1557.
