### ISSUE TITLE
SDataClient.Get requires first parameter (key)

### ISSUE THREAD

**Issue by bafadam** [Saleslogix/DotNetSDataClient#11]
SDataClient.Get requires the first parameter (key). If this value is blank or null, it throws an Exception "Additional information: Value cannot be empty."

When pulling the values for a template, the Get request requires a key for a value. I think that's actually an error because the test application doesn't send one in and is throwing the same exception.

Thanks!

**Comment by NathanBaulch** [comment]
This is by design, see: https://github.com/Saleslogix/DotNetSDataClient/wiki/Advanced#templates

**Comment by bafadam** [comment]
Thanks, I'll try reading next time instead of copying code. ;)
