### ISSUE TITLE
Error When Attempting to Post

### ISSUE THREAD

**Issue by scrazzymoto** [Saleslogix/DotNetSDataClient#15]
Got another one for you Nathan. A new requirement in my project is to find the appropriate account manager ID and insert it when creating an account. My code:

```
    class SDataHelper
    {
        [SDataPath("accounts")]
        public class Account
        {
            [SDataProtocolProperty(SDataProtocolProperty.Key)]
            public string Id { get; set; }

            public string AccountName { get; set; }
            public string AccountManagerId { get; set; }
            public string Region { get; set; }

            public string Type = "End Users";
            public string Status = "Active";
        }....

        public Account InsertAccount(string company, string RSM, string region)
        {
            var account = new Account 
                              {
                                AccountName = company,
                                AccountManagerId = RSM,
                                Region = region    
                              };

            account = _client.Post(account);

            return account;
        }
```
However, upon the attempted post, I get the following error:

> Invalid index 14 for this OleDbParameterCollection with Count=14.

After some Googling, it appears that it might be that Account Manager ID is being mapped twice? I know that earlier, before this new requirement, the business logic was creating the accounts with "ADMIN" in the Account Manager ID field. Any insight?

**Comment by NathanBaulch** [comment]
I wasn't able to reproduce your error but in general you should use a resource property for relationships like this. In your particular case, rename the property to `AccountManager` and pass it an instance with just the `Key` property populated. You can use either a typed User object if you have one or an untyped `SDataResource`.

```csharp
var account = new Account
    {
        AccountName = company,
        AccountManager = new SDataResource {Key = RSM},
        Region = region
    };
account = client.Post(account);
```

**Comment by scrazzymoto** [comment]
Thanks Nathan, will try that!

**Comment by scrazzymoto** [comment]
That did the trick! Now why did that work as opposed to the way I was doing it?

**Comment by NathanBaulch** [comment]
I can't say off the top of my head but that would be a server-side issue.

**Comment by scrazzymoto** [comment]
Got it, thanks again!
