### ISSUE TITLE
DATABASE LAYER: [SECPROFILE].[PROFILEDATA]

### ISSUE THREAD

**Issue by zeves095** [Saleslogix/DotNetSDataClient#16]
1. The number of bits is allocated for the rights for table field after the field offset in profiledata field?
2. how (format) in the designated bits are encrypted right?

**Comment by NathanBaulch** [comment]
It's hard to tell from the little information you've given, but this sounds like a server-side question. This repository focuses on the consumption of SData endpoints from .net clients.

**Comment by zeves095** [comment]
Yes, this is question about database layer of SalesLogix Sales.

There is http://developer.saleslogix.com/DotNetSDataClient/whitepaper/system_security.html in documentation . It say: about SECPROFILE table. There is field PROFILEDATA In this table. It's BLOB and contain rights per table-fields... 

I have'nt found email for support for that product and so - i written here - maybe you can help me.


So - the question is how to get from DB <blob> field rights per field manual... without Security API.

**Comment by NathanBaulch** [comment]
You need to manually parse the `SecProfile.ProfileData` format? This definitely isn't the right forum to discuss something like that, but I can tell you that it's a base64 flavor string with three field access flags packed into each decoded byte (highest two bits ignored). Good luck!

**Comment by zeves095** [comment]
Thnx you mach!!!
