### ISSUE TITLE
Batch Commit Not returning IDs

### ISSUE THREAD

**Issue by bafadam** [Saleslogix/DotNetSDataClient#18]
I'm doing some simple, synchronous batch processing:

var batch = _client.CreateBatch<SlxAccount>();
batch.PostAll<SlxAccount>(unitsToCreate);
var newAccounts = batch.Commit();

But, it doesn't seem like my newAccounts collection (the one I expect to have an ID) or my unitsToCreate collection (which I don't expect to have an ID) has an account ID when it comes back. Am I missing something there?

Thanks!

**Comment by NathanBaulch** [comment]
The following test code works as expected for me:

```csharp
var batch = client.CreateBatch("accounts");
batch.PostAll(
    new SDataResource {{"AccountName", "_Test1"}},
    new SDataResource {{"AccountName", "_Test2"}},
    new SDataResource {{"AccountName", "_Test3"}});
var accounts = batch.Commit();
foreach (var account in accounts)
{
    Console.WriteLine($"{account.Key}: {account["AccountName"]}");
}
```

What version of SLX are you running against?
Are you using a typed or untyped (`SDataResource`) model in your client app?
Can you provide working sample code that reproduces the problem? `CreateBatch` is a generic method, so your code doesn't compile as is.

**Comment by bafadam** [comment]
I'm sorry, that was my fault. I guess I'd typed that in instead of copy/pasting for some reason.
    [SDataPath("accounts")]
    public class SlxAccount : SlxObject, IDisposable
    {
        public string AccountName { get; set; }
        public string AccountNameUpper { get; set; }
        public string Aka { get; set; }
        public string AlternateKeyPrefix { get; set; }
        public string AlternateKeySuffix { get; set; }
        public string AlternatePhone { get; set; }
        public string BusinessDescription { get; set; }
        //this continues on 
}

 var batch = _client.CreateBatch<SlxAccount>();
 batch.PostAll<SlxAccount>(unitsToCreate);
 var newAccounts = batch.Commit();

**Comment by bafadam** [comment]
` var batch = _client.CreateBatch<SlxAccount>();
 batch.PostAll<SlxAccount>(unitsToCreate);
 var newAccounts = batch.Commit();`

**Comment by NathanBaulch** [comment]
You need to answer my other questions before I can help further.
