### ISSUE TITLE
How to handle failures in batch put?

### ISSUE THREAD

**Issue by jegarne** [Saleslogix/DotNetSDataClient#19]
Is it possible to tell which records failed and were successful from a batch PUT?  Is there any flag returned on the objects? For example, with POST you can assume that there was a problem if an ID was not returned.  Thanks.

**Comment by NathanBaulch** [comment]
You're looking for the `HttpStatus` and `Diagnoses` protocol properties on the resources returned.

The following example executes a batch of 3 account GET requests that includes a non-existent ID. Failed batch items have a HTTP status above `400` along with a diagnosis explaining the reason.

```csharp
var batch = client.CreateBatch("accounts");
batch.GetAll("AA2EK0013017", "AA2EK0013016", "AA2EK0013019");
var accounts = batch.Commit();
foreach (var account in accounts)
{
    Console.Write(account.Key + ":");
    if (account.HttpStatus < HttpStatusCode.BadRequest)
    {
        Console.WriteLine(account["AccountName"]);
    }
    else
    {
        foreach (var diagnosis in account.Diagnoses)
        {
            Console.WriteLine(diagnosis.Message);
        }
    }
}
```

If you're using a typed model then you'll need to add the following properties to your objects:

```csharp
[SDataProtocolProperty] public HttpStatusCode? HttpStatus { get; set; }
[SDataProtocolProperty] public Diagnoses Diagnoses { get; set; }
```

**Comment by jegarne** [comment]
Perfect.  That's very useful.  It's probably worth copying that over to the wiki.
