### ISSUE TITLE
Update using DifferentialUpdate.

### ISSUE THREAD

**Issue by joeshmoe301** [Saleslogix/DotNetSDataClient#21]
Do you have any example code on how to implement the IChangeTracking interface?  I am having difficulties getting an update to work that will only update properties that have changes.

Thanks.

**Comment by NathanBaulch** [comment]
`IChangeTracking` is a simple interface that's deceptively difficult to implement, especially if you want to support relationships and rollback. Your POCO needs to keep track of all properties that have changed since the last time `AcceptChanges` was called and provide those changes (usually in the form of a `IDictionary<string, object>`) when `GetChanges` is called.

Here's a primitive implementation:

```csharp
public class Account : IChangeTracking
{
    private readonly IDictionary<string, object> _changes = new Dictionary<string, object>();

    private string _accountName;
    private string _type;

    public string AccountName
    {
        get { return _accountName; }
        set { Set(nameof(AccountName), out _accountName, value); }
    }

    public string Type
    {
        get { return _type; }
        set { Set(nameof(Type), out _type, value); }
    }

    private void Set<T>(string name, out T field, T value)
    {
        field = value;
        _changes[name] = value;
    }

    public bool IsChanged => _changes.Count > 0;

    public object GetChanges()
    {
        return _changes;
    }

    public void AcceptChanges()
    {
        _changes.Clear();
    }
}
```

Note that properties will still be included in the change set even if the consumer sets them back to their original value. If you want to support rollback via `IRevertibleChangeTracking` then you'll need to keep track of your POCO's original state also.

I recommend you study the `SDataResource` code for a complete implementation.

**Comment by joeshmoe301** [comment]
Thank you for the response and example code.

**Comment by joeshmoe301** [comment]
Based on your example, I have been able to successfully implement IChangeTracking, except for nested objects.  I have a contact class and address class.  Both implement IChangeTracking.  Updating each class individually works and only updates modified properties.  When I Update a contact with an address in the same Put (using SDataPayloadOptions), the contact is updated correctly (only properties flagged as changed are updated), but the address is not (all fields are updated in the database).

Suggestions?

Thanks.

**Comment by NathanBaulch** [comment]
Your `GetChanges` method needs to also check relationship properties that happen to implement `IChangeTracking`.

A very simple implementation might look like this:

```csharp
public object GetChanges()
{
    if (Address != null && Address.HasChanges)
    {
        _changes["Address"] = Address.GetChanges();
    }
    else
    {
        _changes.Remove("Address");
    }

    return _changes;
}
```

As you can probably see by now, change tracking certainly complicates your model/DTOs. If I had more time to work on this library then I'd probably implement a "session" type object that maintains the original snapshot and automatically generates change sets for any kind of object (just like NHibernate sessions).

**Comment by joeshmoe301** [comment]
Thank you.  I implemented the code above (and it makes sense), but the address is still not being updated correctly.  When debugging though, I noticed that the address record is not being updated, but a new address record is being created.  I determined this by looking at the address key that was pulled before the update and then looking at the address key after.  using a browser to go to the old key, domain/sdata/slx/dynamic/-/addresses('a8KD5A000C7W'), and the new key, /sdata/slx/dynamic/-/addresses('a8KD5A000C7X'), shows that they both still exist, but the contact is associated with the new key.

Maybe this is how updates work in Infor in order to keep a history, but I would have thought the record would be updated.  Assuming the record should be updated, then I am doing something wrong in my other code.

Do you know if the record should be updated or a new one created?

I'm using this to pull the existing record (in this case, I don't have an id, just first and last name):

Here is my code:
`var checkContact = client.Query<Contact>()
                    .Where(c => c.FirstName == FirstName && c.LastName == LastName)
                    .OrderBy(c => c.LastName)
                    .ThenBy(c => c.FirstName)
                    .Fetch(c => c.Address)
                    .FirstOrDefault();

                if (checkContact != null)
                {
                    this.Id = checkContact.Id;
                    this.Address.Key = checkContact.Address.Key;
                    client.DifferentialUpdate = true;
                    var contactOptions = new SDataPayloadOptions { Include = "Address" };
                    var contact = client.Put(this, null, contactOptions);
                }`

**Comment by NathanBaulch** [comment]
That would indicate that the nested entity didn't have a key specified, which makes sense based on the sample code I sent. You'll need to change the internal `_changes` dictionary into a `SDataResource` on all your entities (or a common base class) and make sure you set the `Key` property before returning it:

```csharp
private readonly SDataResource _changes = new SDataResource();

[SDataProtocolProperty]
public string Key { get; set; }

public object GetChanges()
{
    _changes.Key = Key;

    //TODO: relationships

    return _changes;
}
```

**Comment by joeshmoe301** [comment]
That worked.  Thank you for your time and patience.
