### ISSUE TITLE
Cannot Query?

### ISSUE THREAD

**Issue by johnfoster** [Saleslogix/DotNetSDataClient#4]
I've built the assemblies and referenced them in my project.  I can access client.Get<>, etc, but I cannot access client.Query.  My reference is to the 4.0 runtime version of SalesLogix.SData.Client, and my project is also .NET 4.0.

**Comment by NathanBaulch** [comment]
Have you added a using directive for `Saleslogix.SData.Client.Linq`? The `Query` method is an extension method defined in the `Linq

**Comment by johnfoster** [comment]
Arg!


That was it. Thanks Nathan.


Regards,

 

John
