### ISSUE TITLE
Not able to update Account.Owner or Account.AccountManager

### ISSUE THREAD

**Issue by johnfoster** [Saleslogix/DotNetSDataClient#8]
The following code doesn't update the Owner or the Account Manager.  No errors, but no update either...

                SDataPayloadOptions options = new SDataPayloadOptions { Include = "Address,Owner,AccountManager" };
                account = Globals.client.Get<Account>(accountId, null, options);
                //Globals.client.DifferentialUpdate = true;
                account.Owner = defaultOwner;
                account.AccountManager = defaultAccountManager;
                options = new SDataPayloadOptions { Include = "Address,Owner,AccountManager" };
                account = Globals.client.Post(account, null, options);

    [SDataPath("accounts")]
    public class Account
    {
        [SDataProtocolProperty(SDataProtocolProperty.Key)]
        public string Id { get; set; }
        public string AccountName { get; set; }
        public Owner Owner { get; set; }
        public User AccountManager { get; set; }
        public Address Address { get; set; }
    }

**Comment by NathanBaulch** [comment]
Sorry for the late response. It sounds like you should be calling `Put` (update) rather than `Post` (create) in your example.
