### ISSUE TITLE
client.Put(object) - Unable to extract resource key from target

### ISSUE THREAD

**Issue by Amd3202** [Saleslogix/DotNetSDataClient#9]
Hello,

When following the Create example from the link below. If the Id is left as blank/default; String.Empty; or Null the error "Unable to extract resource key from target" is thrown. However, if a real Id is specified then the UPDATE executes perfectly. So the issue is that with the example I am unable to INSERT. 
Here's a link to the example i'm following https://github.com/Saleslogix/DotNetSDataClient/wiki/Resources 

Contact co = new Contact { FirstName = "BOB", FullName = "Bob Smit666", LastName = "Smit666", ModifyDate = DateTime.Now, Status = "New" };

client = new SDataClient(url)
                {
                    UserName = username,
                    Password = pass                    
                };
                co = client.Put(co);

[SDataPath("contacts")]
    public class Contact
    {
        [SDataProtocolProperty(SDataProtocolProperty.Key)]
        public string Id { get; set; }

        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string Status { get; set; }
        public string Email { get; set; }
        public string WorkPhone { get; set; }
        public string Title { get; set; }
       
        public DateTime? ModifyDate { get; set; }
    }

**Comment by johnfoster** [comment]
Put is UPDATE, Post is CREATE

**Comment by Amd3202** [comment]
Oh MY! Wow thanks, it's right there on the documentation i liked too as well. Not sure how i missed that. I guess that's what Late nights do for you. Thanks for the note it works perfectly.
